tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
vscode:
  extensions:
    - mechatroner.rainbow-csv@1.3.1:MGIjKVd23K6AiUfh4hYKNw==
image:
  file: .gitpod.Dockerfile